server:
 port: 9090
 
spring:
 datasource:
  url: jdbc:mysql://localhost/testdb
  username: root
  password: root
  initialize: false

 jpa:
  show-sql: true


# security:
 oauth2:
   resource:
     jwt:
       keyUri: http://localhost:8080/auth/oauth/token_key

  
logging:
 level:
  root: INFO